/**
 * 契约生成器（阶段 1）：把「组件类型名 / 命令名 / 关键常量」从它们的**唯一来源**
 * 产出到几份手抄副本（e2e helper、Unity C# 常量）。
 *
 * 唯一来源：
 * - 组件类型名 → `@dts/document` 的 `COMPONENT_TYPES`；
 * - 命令种类   → `@dts/protocol` 的 `commandRequestSchema` 的判别值（运行时从 zod 取，不新增手写清单）；
 * - 常量       → `@dts/document` 的 `DOCUMENT_FORMAT_VERSION` / `FOG_DEFAULT_SORTING_ORDER`。
 *
 * 用法：
 *   pnpm gen:contract      # 写生成物
 *   pnpm check:contract    # 只比对，不一致退出 1（挂进 pnpm check）
 *
 * **不要手改生成物**：改了源就重新生成；忘了生成由 `check:contract` 拦下。
 * 详见 `docs/PLAN-单一数据源与codegen.md`。
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
// 直接引源文件（生成器在 `scripts/` 下、不属于任何 workspace 包，按相对路径解析最省事；
// 包内部的 `@dts/grid` 依赖由各自的 node_modules 解析，不受影响）。
import {
  COMPONENT_TYPES,
  DOCUMENT_FORMAT_VERSION,
  FOG_DEFAULT_SORTING_ORDER,
} from "../packages/document/src/index";
import { commandRequestSchema } from "../packages/protocol/src/messages";
// `scripts/` 不是 workspace 包，拿不到 `zod` 的顶层符号；借文档包自己那份（同一个 store 实例）。
import { z } from "../packages/document/node_modules/zod";
import * as documentContract from "../packages/document/src/index";
import * as protocolContract from "../packages/protocol/src/messages";

const SERVER_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const WORKSPACE_ROOT = resolve(SERVER_ROOT, "..");

/**
 * C# 侧组件常量名（**唯一手工表**）。
 *
 * C# 的常量名与组件类型名不同名（`Map` / `Image` / `Video` …），所以必须有这张对照表。
 * 加一个组件时：源里加完组件，若想给 C# 一个不同的别名，就在这儿加一行；
 * 不加的话默认用类型名本身（`PascalCase` 已是合法标识符）。
 */
const CSHARP_COMPONENT_NAMES: Record<string, string> = {
  GridMap: "Map",
  FogOfWar: "FogOfWar",
  ImageLayer: "Image",
  SpriteLayer: "Sprite",
  PlaySound: "Sound",
  Teleport: "Teleport",
  Magnifier: "Magnifier",
  VideoOverlay: "Video",
  VideoBlend: "VideoBlend",
};

interface CommandLiteralOption {
  shape: { kind: { value: string } };
}

/** 命令判别值（顺序 = schema 里声明的顺序）。 */
const COMMAND_KINDS: readonly string[] = (
  commandRequestSchema.options as unknown as readonly CommandLiteralOption[]
).map((option) => option.shape.kind.value);

/** 首字母小写：`GridMap` → `gridMap`（e2e `COMPONENT` 的键约定）。 */
function lowerFirst(value: string): string {
  return value.charAt(0).toLowerCase() + value.slice(1);
}

/** `play_sound` → `PlaySound`（C# 常量名 `CommandPlaySound` 的后半段）。 */
function pascalCase(value: string): string {
  return value
    .split(/[^A-Za-z0-9]+/)
    .filter((part) => part.length > 0)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

const GENERATED_BANNER = "本文件由 server/scripts/gen-contract.ts 生成，请勿手改。";

// ---------------------------------------------------------------- e2e 生成物

function renderE2eContract(): string {
  const components = COMPONENT_TYPES.map(
    (def) => `  ${lowerFirst(def.type)}: "${def.type}",`,
  ).join("\n");

  return `// <auto-generated>
// ${GENERATED_BANNER}
// 重新生成：pnpm gen:contract    校验：pnpm check:contract
// </auto-generated>

/**
 * e2e 复述的契约常量（e2e 不引用内部包，所以由 \`scripts/gen-contract.ts\` 生成一份）。
 *
 * 手改这里没有意义——改了源忘了重新生成，\`pnpm check:contract\` 会失败。
 */

/** 场景文件的当前格式版本（源：@dts/document 的 DOCUMENT_FORMAT_VERSION）。 */
export const CURRENT_SCENE_FORMAT_VERSION = ${DOCUMENT_FORMAT_VERSION};

/** 战争雾雾层显示顺序的缺省值（源：@dts/document 的 FOG_DEFAULT_SORTING_ORDER）。 */
export const FOG_DEFAULT_SORTING_ORDER = ${FOG_DEFAULT_SORTING_ORDER};

/** 承载对象特性的组件类型名（源：@dts/document 的 COMPONENT_TYPES）。 */
export const COMPONENT = {
${components}
} as const;
`;
}

// ---------------------------------------------------------------- C# 生成物

function renderCsharpContract(): string {
  const componentMembers = COMPONENT_TYPES.map((def) => {
    const name = CSHARP_COMPONENT_NAMES[def.type] ?? def.type;
    const summary = def.tooltip ?? def.displayName;
    return `            /// <summary>${def.displayName}：${summary}</summary>\n            public const string ${name} = "${def.type}";`;
  }).join("\n\n");

  const commandMembers = COMMAND_KINDS.map(
    (kind) => `        public const string Command${pascalCase(kind)} = "${kind}";`,
  ).join("\n");

  return `// <auto-generated>
// ${GENERATED_BANNER}
// 重新生成：pnpm gen:contract    校验：pnpm check:contract
// </auto-generated>
namespace DiceTale
{
    public static partial class Protocol
    {
        /// <summary>对象特性组件的类型名（源：@dts/document 的 COMPONENT_TYPES）。</summary>
        public static partial class ComponentType
        {
${componentMembers}
        }

        // 命令种类（源：@dts/protocol 的 commandRequestSchema 判别值）
${commandMembers}
    }
}
`;
}

// ---------------------------------------------------------------- 结构一致性（两侧复刻 schema）

/**
 * 两侧**有意**保留的差异（不是漂移，比对时各自剥掉）：
 * - 文档专有 `guid`：磁盘上的素材身份，推送时由 `resolveSceneSprites` 剥掉（前端只认路径 ID）；
 * - 载荷专有 `spriteGrid`：推送时按素材 meta 解析出来的「几列几行」，落盘不写。
 */
const DOC_ONLY_KEYS: ReadonlySet<string> = new Set(["guid"]);
const PROTO_ONLY_KEYS: ReadonlySet<string> = new Set(["spriteGrid"]);

/**
 * 「同一份数据形状」在两侧的复刻对照：协议不能依赖文档包，所以两边各手写一份，
 * **必须逐字一致**（字段名 / 可选性 / 默认值 / 约束）。这里用 `z.toJSONSchema` 把两份
 * zod schema 都摊平成 JSON Schema 再逐路径比——比抽样断言更能兜住悄悄漂移（见审计 B5）。
 */
const SCHEMA_PAIRS: readonly { name: string; doc: unknown; proto: unknown }[] = [
  { name: "GridMap", doc: documentContract.mapDataSchema, proto: protocolContract.mapDataSchema },
  { name: "FogOfWar", doc: documentContract.mapFogSchema, proto: protocolContract.mapFogSchema },
  {
    name: "ImageLayer / SpriteLayer",
    doc: documentContract.imageLayerDataSchema,
    proto: protocolContract.imageLayerDataSchema,
  },
  { name: "PlaySound", doc: documentContract.soundDataSchema, proto: protocolContract.soundDataSchema },
  { name: "Teleport", doc: documentContract.teleportDataSchema, proto: protocolContract.teleportDataSchema },
  {
    name: "Magnifier",
    doc: documentContract.magnifierDataSchema,
    proto: protocolContract.magnifierDataSchema,
  },
  {
    name: "Magnifier 状态",
    doc: documentContract.magnifierStateSchema,
    proto: protocolContract.magnifierStateSchema,
  },
  { name: "VideoOverlay", doc: documentContract.videoDataSchema, proto: protocolContract.videoDataSchema },
  {
    name: "VideoBlend",
    doc: documentContract.videoBlendDataSchema,
    proto: protocolContract.videoBlendDataSchema,
  },
];

function toJsonSchema(schema: unknown): unknown {
  return z.toJSONSchema(schema as never, { unrepresentable: "any" });
}

/** 递归剥掉指定的对象键。 */
function stripKeys(value: unknown, keys: ReadonlySet<string>): unknown {
  if (Array.isArray(value)) {
    return value.map((item) => stripKeys(item, keys));
  }

  if (value !== null && typeof value === "object") {
    const out: Record<string, unknown> = {};
    for (const [key, item] of Object.entries(value as Record<string, unknown>)) {
      if (keys.has(key)) continue;
      out[key] = stripKeys(item, keys);
    }

    return out;
  }

  return value;
}

/** 逐路径比较两份 JSON 值，返回人类可读的差异行（键顺序无关）。 */
function schemaDiff(a: unknown, b: unknown, path = ""): string[] {
  if (a === b) return [];
  const label = path === "" ? "(root)" : path;
  const aObject = a !== null && typeof a === "object";
  const bObject = b !== null && typeof b === "object";
  if (!aObject || !bObject) {
    if (aObject !== bObject || typeof a !== typeof b) {
      return [`${label}: 类型不同（doc=${typeof a} / proto=${typeof b}）`];
    }

    return [`${label}: doc=${JSON.stringify(a)} proto=${JSON.stringify(b)}`];
  }

  if (Array.isArray(a) !== Array.isArray(b)) {
    return [`${label}: 结构不同（数组 / 对象）`];
  }

  if (Array.isArray(a) && Array.isArray(b)) {
    if (a.length !== b.length) return [`${label}: 数组长度不同（${a.length} / ${b.length}）`];
    return a.flatMap((item, index) => schemaDiff(item, b[index], `${path}[${index}]`));
  }

  const aRecord = a as Record<string, unknown>;
  const bRecord = b as Record<string, unknown>;
  const lines: string[] = [];
  for (const key of new Set([...Object.keys(aRecord), ...Object.keys(bRecord)])) {
    const child = path === "" ? key : `${path}.${key}`;
    if (!(key in aRecord)) {
      lines.push(`${child}: 只有协议侧有`);
    } else if (!(key in bRecord)) {
      lines.push(`${child}: 只有文档侧有`);
    } else {
      lines.push(...schemaDiff(aRecord[key], bRecord[key], child));
    }
  }

  return lines;
}

/** 两份复刻 schema 的结构差异（已剔除有意的两侧专有键）。 */
function checkSchemaConsistency(): string[] {
  const problems: string[] = [];
  for (const pair of SCHEMA_PAIRS) {
    const docJson = stripKeys(toJsonSchema(pair.doc), DOC_ONLY_KEYS);
    const protoJson = stripKeys(toJsonSchema(pair.proto), PROTO_ONLY_KEYS);
    for (const line of schemaDiff(docJson, protoJson)) {
      problems.push(`[${pair.name}] ${line}`);
    }
  }

  return problems;
}

// ---------------------------------------------------------------- 写出 / 校验

const OUTPUTS: readonly { path: string; content: string }[] = [
  { path: join(SERVER_ROOT, "e2e", "helpers", "generated", "contract.ts"), content: renderE2eContract() },
  {
    path: join(WORKSPACE_ROOT, "client", "Assets", "DiceTale", "Scripts", "Generated", "GeneratedContract.g.cs"),
    content: renderCsharpContract(),
  },
];

/** 统一换行成 LF（仓库源码是 LF；Windows 上 WriteFile 默认不转换，但显式一点）。 */
function normalize(text: string): string {
  return text.replace(/\r\n/g, "\n");
}

const checkMode = process.argv.includes("--check");
const mismatches: string[] = [];

for (const output of OUTPUTS) {
  const expected = normalize(output.content);
  if (checkMode) {
    let actual: string | undefined;
    try {
      actual = normalize(readFileSync(output.path, "utf8"));
    } catch {
      actual = undefined;
    }

    if (actual !== expected) {
      mismatches.push(actual === undefined ? `缺失生成物：${output.path}` : `生成物与源不一致：${output.path}`);
    }
    continue;
  }

  mkdirSync(dirname(output.path), { recursive: true });
  writeFileSync(output.path, expected, "utf8");
  console.log(`已生成 ${relativeFromServer(output.path)}`);
}

if (checkMode) {
  const schemaProblems = checkSchemaConsistency();

  if (mismatches.length > 0) {
    console.error("契约生成物已过期（改了源就重新生成）：");
    for (const item of mismatches) {
      console.error(`  ✗ ${item}`);
    }

    console.error("\n重新生成：pnpm gen:contract");
  }

  if (schemaProblems.length > 0) {
    console.error("协议 / 文档的复刻 schema 已漂移（字段名 / 默认值 / 约束必须逐字一致）：");
    for (const item of schemaProblems) {
      console.error(`  ✗ ${item}`);
    }

    console.error("\n对齐两边（有意的差异写进 DOC_ONLY_KEYS / PROTO_ONLY_KEYS）后重跑。");
  }

  if (mismatches.length > 0 || schemaProblems.length > 0) {
    process.exit(1);
  }

  console.log(
    `契约一致：组件 ${COMPONENT_TYPES.length} 种 / 命令 ${COMMAND_KINDS.length} 条；` +
      `复刻 schema ${SCHEMA_PAIRS.length} 组结构对齐（忽略 ${DOC_ONLY_KEYS.size + PROTO_ONLY_KEYS.size} 个有意的两侧专有键）。`,
  );
}

function relativeFromServer(path: string): string {
  return path.startsWith(SERVER_ROOT) ? path.slice(SERVER_ROOT.length + 1) : path;
}
